[project]
name = "rand-selection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Victoria Ten", email = "tenv@mcmaster.ca" }
]
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.64.0",
]

[project.scripts]
rand-selection = "rand_selection.cli:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
